### ISSUE TITLE
Update the Quickstart section of the readme

### ISSUE THREAD

**Issue by jsenecal** [emehrkay/gizmo#2]
https://github.com/emehrkay/gizmo#quickstart does not reflect actual project status.
- gizmo.request.Binary does not exist
- BinaryRequest() is not imported
- Gremlin() is not imported

I stopped there...

**Comment by emehrkay** [comment]
Check it out now. I just made a minor change to that section in the README. I plan on rewriting the whole thing and creating some real documentation pretty soon.

**Comment by emehrkay** [comment]
The underlying library changed to be async by default, but you can still use it in a blocking manner. I've updated the quick start to reflect this change. Let me know if you find anything else.

**Comment by jsenecal** [comment]
Thanks, I'll take a look at it.
